# Generated by Django 4.2.4 on 2023-08-25 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_userhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserHistory',
        ),
    ]
